language: scala

dist: xenial

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

jdk:
  - openjdk8

sudo: false

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/aa4425cc96aee/sbt && chmod +x ./sbt
  - ./sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck "++${TRAVIS_SCALA_VERSION}!" checkGenerateCodeError compile test:compile scalapropsTestNames scalapropsJS/test scalapropsJVM/test scalazJS/test scalazJVM/test "project /" publishLocal
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
  - if [[ ${JAVA_HOME} == $(jdk_switcher home openjdk11) ]]; then rm -rf $HOME/.ivy2/cache ; fi

matrix:
  include:
    - name: dotty
      scala: 0.21.0-RC1
      script:
      - sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck "++${TRAVIS_SCALA_VERSION}!" checkGenerateCodeError scalapropsJVM/test:compile scalapropsJVM/test scalazJVM/test rootJVM/publishLocal
    - scala: SCALA_NATIVE
      jdk: openjdk8
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/aa4425cc96aee/sbt && chmod +x ./sbt
      script:
      - ./sbt -J-Xmx5G rootNative/compile scalapropsNative/test scalazNative/test
    - scala: 2.12.10
      jdk: openjdk11
      script:
      - java -version
      - sbt "++${TRAVIS_SCALA_VERSION}!" scalapropsJS/test scalapropsJVM/test scalazJS/test scalazJVM/test "project /" publishLocal
    - os: windows
      language: bash
      env:
      - JDK="adopt@1.8.0-222"
      before_install:
      - curl "https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh" --output .install-jdk-travis.sh
      - source .install-jdk-travis.sh
      script:
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/aa4425cc96aee/sbt && chmod +x ./sbt
      - ./sbt "++ 2.13.1" compile test:compile scalapropsJVM/test scalazJVM/test "project /" publishLocal
